name: 'CleanTalk Anti-Spam banners tests'
author: 'CleanTalk Team'

inputs:
  DB_HOST:
    required: false
    default: 'localhost'
    description: 'DB hostname'
runs:
  using: 'composite'
  steps:
    - run: export PYTHONPATH="${{ github.workspace }}"
      shell: bash
    - run: |
        python -m pip install --upgrade pip
        pip install selenium python-dotenv requests mysqlclient phpserialize
      shell: bash
    - run: python ${{ github.action_path }}/apbct_check_banners.py
      shell: bash
