name: 'CleanTalk Anti-Spam banners tests'
author: 'CleanTalk Team'

inputs:
  auth_url:
    required: false
    default: 'http://localhost:8080/wp-admin/'
    description: 'Admin login url'
  auth_login:
    required: false
    default: 'admin'
    description: 'Admin name'
  auth_password:
    required: false
    default: 'password'
    description: 'Admin pass'
  DB_HOST:
    required: false
    default: 'localhost'
    description: 'DB hostname'
runs:
  using: 'composite'
  steps:
    - run: export PYTHONPATH="${{ github.workspace }}"
      shell: bash
    - run: |
        python -m pip install --upgrade pip
        pip install selenium python-dotenv requests mysqlclient phpserialize
      shell: bash
    - run: python ${{ github.action_path }}/apbct_check_banners.py
      shell: bash
