from dotenv import load_dotenv
import os

load_dotenv()

BANNERS_TESTS_HEADLESS = os.getenv('BANNERS_TESTS_HEADLESS', 'yes')
BANNERS_TESTS_JS_ON = os.getenv('BANNERS_TESTS_JS_ON', 'yes')
BANNERS_TESTS_REGULAR_TIMEOUT = os.getenv('BANNERS_TESTS_REGULAR_TIMEOUT', 10)

BANNERS_TESTS_URL = os.getenv('BANNERS_TESTS_URL', 'http://localhost:8080')
BANNERS_TESTS_AUTH_LOGIN = os.getenv('BANNERS_TESTS_AUTH_LOGIN', 'admin')
BANNERS_TESTS_AUTH_PASS = os.getenv('BANNERS_TESTS_AUTH_PASS', 'password')
BANNERS_TESTS_SETTINGS_URL = BANNERS_TESTS_URL + '/wp-admin/options-general.php?page=cleantalk'
BANNERS_TESTS_PLUGINS_URL = BANNERS_TESTS_URL + '/wp-admin/plugins.php'

BANNERS_TESTS_API_KEY_REGULAR = os.getenv('BANNERS_TESTS_API_KEY_REGULAR', '')
BANNERS_TESTS_API_KEY_REVIEW = os.getenv('BANNERS_TESTS_KEY_REVIEW', '')
BANNERS_TESTS_API_KEY_TRIAL_EXPIRED = os.getenv('BANNERS_TESTS_KEY_REVIEW', '')
BANNERS_TESTS_API_KEY_PAID_EXPIRED = os.getenv('BANNERS_TESTS_KEY_REVIEW', '')
