from dotenv import load_dotenv
import os

load_dotenv()

print('CHECK ENV')
os.getenv('INPUT_DB_HOST')

# Database settings
BANNERS_TESTS_DB_HOST = os.getenv('INPUT_DB_HOST', 'localhost')
BANNERS_TESTS_DB_NAME = os.getenv('BANNERS_TESTS_DB_NAME', 'wordpress')
BANNERS_TESTS_DB_USER = os.getenv('BANNERS_TESTS_DB_USER', 'wordpress')
BANNERS_TESTS_DB_PASSWORD = os.getenv('BANNERS_TESTS_DB_PASSWORD', 'password')
BANNERS_TESTS_DB_PORT = os.getenv('BANNERS_TESTS_DB_PORT', '3306')

BANNERS_TESTS_HEADLESS = os.getenv('BANNERS_TESTS_HEADLESS', 'yes')
BANNERS_TESTS_JS_ON = os.getenv('BANNERS_TESTS_JS_ON', 'yes')
BANNERS_TESTS_REGULAR_TIMEOUT = os.getenv('BANNERS_TESTS_REGULAR_TIMEOUT', 10)

BANNERS_TESTS_URL = os.getenv('BANNERS_TESTS_URL', 'http://localhost:8080')
BANNERS_TESTS_AUTH_LOGIN = os.getenv('BANNERS_TESTS_AUTH_LOGIN', 'admin')
BANNERS_TESTS_AUTH_PASS = os.getenv('BANNERS_TESTS_AUTH_PASS', 'password')
BANNERS_TESTS_SETTINGS_URL = BANNERS_TESTS_URL + '/wp-admin/options-general.php?page=cleantalk'
BANNERS_TESTS_PLUGINS_URL = BANNERS_TESTS_URL + '/wp-admin/plugins.php'

BANNERS_TESTS_API_KEY_REGULAR = os.getenv('BANNERS_TESTS_API_KEY_REGULAR', '')
BANNERS_TESTS_API_KEY_REVIEW = os.getenv('BANNERS_TESTS_API_KEY_REVIEW', '')
BANNERS_TESTS_API_KEY_TRIAL_EXPIRED = os.getenv('BANNERS_TESTS_API_KEY_TRIAL_EXPIRED', '')
BANNERS_TESTS_API_KEY_PAID_EXPIRED = os.getenv('BANNERS_TESTS_API_KEY_PAID_EXPIRED', '')
